# Class matchers
JetBrainsIDE    = /jetbrains-/i
ZenBrowser      = /^navigator$/i
Chrome          = "google-chrome"
Browser         = /chrome|chromium|lights-ui|crx_|outlook|navigator|firefox/i
Terminal        = /kitty|tmux|helix/i
KittyScratch    = /^kitty_scratch$/i
Obsidian        = "obsidian"
Slack           = "slack"
TeamsForLinux   = /^teams-(\w+)/
TogglTrack      = /crx_chpiljhfemlfpnfoohpbokdofonkiifm/i
VSCode          = /Code/i

# vim: ft=ini sw=2 ts=2 sts=2 expandtab foldmethod=indent

