@include "include/class_matchers.conf"
@include "include/utils.conf"

# Replace trigger string with the second argument
trigger  = ? "$0" >> repeat[Backspace, sub[length["$0"], 1]] $1

# Autocomplete trigger string with the second argument
complete = ? "$0" Tab >> $1

# Format date
format_date = $(date +"$0")

@include "include/.private.conf"

[default]
  trigger[":time", type[format_date["%H:%M:%S"]]]
  trigger[":dts",  type[format_date["%Y-%m-%d-%H-%M"]]]
  trigger[":ds",   type[format_date["%Y-%m-%d"]]]
  trigger[":rel",  type[format_date["%Y%m%d.0"]]]
  trigger[":uuid", type[$(uuidgen)]]
  trigger[":ip",   type[$(dig @resolver1.opendns.com ANY myip.opendns.com +short)]]

  trigger["//24",  type["255.255.255.0"]]
  trigger["//16",  type["255.255.0.0"]]
  trigger["//8",   type["255.0.0.0"]]
  trigger["192..", type["192.168."]]
  trigger["..2",   type["192.168.2."]]
  trigger["..5",   type["192.168.5."]]
  trigger["..6",   type["192.168.6."]]
  trigger["..9",   type["192.168.99."]]

  complete["192",  type[".168."]]

  # Solarized Dark Black palette
  trigger[":bg00",   type["#000000"]]
  trigger[":bg05",   type["#141414"]]
  trigger[":bg10",   type["#212121"]]
  trigger[":bg15",   type["#272727"]]
  trigger[":bg20",   type["#2e2e2e"]]
  trigger[":bg30",   type["#3a3a3a"]]
  trigger[":bg40",   type["#4a4a4a"]]
  trigger[":base03", type["#002b36"]]
  trigger[":base02", type["#073642"]]
  trigger[":base01", type["#586e75"]]
  trigger[":base00", type["#657b83"]]
  trigger[":base0",  type["#839496"]]
  trigger[":base1",  type["#93a1a1"]]
  trigger[":base2",  type["#eee8d5"]]
  trigger[":base3",  type["#fdf6e3"]]
  trigger[":yellow", type["#b58900"]]
  trigger[":orange", type["#cb4b16"]]
  trigger[":red",    type["#dc322f"]]
  trigger[":magenta",type["#d33682"]]
  trigger[":violet", type["#6c71c4"]]
  trigger[":blue",   type["#268bd2"]]
  trigger[":cyan",   type["#2aa198"]]
  trigger[":green",  type["#859900"]]

[class = Terminal]
  trigger["#bash", type["#!/usr/bin/env bash\n\n"]]
  trigger["#zsh",  type['#!/usr/bin/env zsh\n\n']]

# vim: ft=ini sw=2 ts=2 sts=2 expandtab foldmethod=indent
