@include "include/class_matchers.conf"

# Replace trigger string with the second argument
trigger = ? "$0" >> repeat[Backspace, sub[length["$0"], 1]] $1

# Format date
format_date = $(date +"$0")

@include "include/.private.conf"

[default]
  trigger[":time", type[format_date["%H:%M:%S"]]]
  trigger[":dts",  type[format_date["%Y-%m-%d-%H-%M"]]]
  trigger[":ds",   type[format_date["%Y-%m-%d"]]]

  trigger["//24", type["255.255.255.0"]]
  trigger["//16", type["255.255.0.0"]]
  trigger["//8", type["255.0.0.0"]]
  trigger["192..", type["192.168."]]

[class = Terminal]
  trigger["#bash", type['#!/usr/bin/env bash\n\n']]
  trigger["#zsh", type['#!/usr/bin/env zsh\n\n']]

# vim: ft=ini sw=2 ts=2 sts=2 expandtab foldmethod=indent
