# Status bar triggered action indicator
EVENT_FIFO   = "/tmp/keymapper-event"

# Keyboard configuration
setKeyboardLayout     = $(gsettings set org.gnome.desktop.input-sources current "$1")
setKeyRepeatDelay     = $(gsettings set org.gnome.desktop.peripherals.keyboard delay $KEY_REPEAT_DELAY)
setKeyRepeatInterval  = $(gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval $KEY_REPEAT_INTERVAL)

# Mouse configuration
setScrollButton       = $(sleep 1 && \
                          xinput set-prop "pointer:Logitech USB Receiver; keymapper" "libinput Button Scrolling Button" 9 && \
                          xinput set-prop "pointer:Logitech USB Receiver; keymapper" "libinput Scroll Method Enabled" 0, 0, 1)
 
# On startup actions
applyInputDeviceConfig = setKeyRepeatDelay setKeyRepeatInterval setScrollButton

# Solarized palette
base01       = "586e75"
base00       = "657b83"
base0        = "839496"
base1        = "93a1a1"
base2        = "eee8d5"
base3        = "fdf6e3"
yellow       = "b58900"
orange       = "cb4b16"
red          = "d30102"
magenta      = "d33682"
violet       = "6c71c4"
blue         = "268bd2"
cyan         = "2aa198"
green        = "859900"

# Macro builder to be used with macro parameter count: $$
switch = $0$1

# Use i3 modes as active context indicators
i3Mode       = $(i3-msg "mode \"$0\"") ^ $(i3-msg "mode \"default\"")

# Send typed output
type   = $(keymapperctl --type "$0")
output = $(keymapperctl --output "$0")
input  = $(keymapperctl --input "$0")

# Logging/debugging
_log1 = $(echo "$0" >> $LOG_FILE)
_log2 = $(pastel --force-color paint "$1" "[$0]" >> $LOG_FILE)

log = switch["_log", $$]["$0", "$1"]

logColor     = $(pastel --force-color paint "$1" "[$0]" >> $LOG_FILE)

stage1       = 50ms log["$0", blue] ^ log["$0", base00]
context      = 50ms log["$0", green] ^ log["$0", base01]
debug        = 50ms log["$0", orange]

write        = $(printf "$0" >> $LOG_FILE)
endWrite     = $(printf "\n" >> $LOG_FILE)

# For notifications and status bar events
event        = $(echo "$0" >> $EVENT_FIFO)
notifyMs     = $(notify-send -t $1 keymapper "$0")
notify       = $(notify-send -t 5000 keymapper "$0")

# Lock/unlock modifiers
keyLockOn    = $(xdotool keydown $0 && touch $STATE_DIR/$0Lock)
keyLockOff   = $(xdotool keyup $0 && rm -f $STATE_DIR/$0Lock)
keyLocksOff  = $(xdotool keyup "Control" keyup "Alt" keyup "Shift" && rm -f $STATE_DIR/$0Lock)

# vim: ft=ini sw=2 ts=2 sts=2 expandtab foldmethod=indent

