# Unmapped abstract action marker
None            = Virtual255

# Virtual modifiers
CapsWord        = Virtual1
AutoShift       = Virtual2
DirectUmlauts   = Virtual3
MouseScrollLock = Virtual4
SpaceMeta       = Virtual5

# Modal states
EditMode        = Virtual20
NavigationMode  = Virtual21
TmuxMode        = Virtual22

# Numpad modes
NumpadNavMode   = Virtual25
NumpadRofiMode  = Virtual26

# vim: ft=ini sw=2 ts=2 sts=2 expandtab foldmethod=indent

